name: CD

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/cd.yml'

jobs:
  deploy-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ./
          keep_files: false
